simple-service:
  application:
    image: ghcr.io/neuralegion/ao-reauth-triggers:latest
    port: 8080
    resources:
      requests:
        cpu: 0.4
        memory: 100Mi
      limits:
        memory: 200Mi
    livenessProbe:
      httpGet:
        path: /
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 120
      periodSeconds: 30

global:
  repeaterIDs: null
  token: null
  cluster: null
  timeout: "30000"
  repeaterImageTag: null
