apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "crapi.fullname" . }}-{{ .Values.chromadb.config.name }}
  labels:
    release: {{ .Release.Name }}
    {{- with .Values.chromadb.config.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  IS_PERSISTENT: {{ .Values.chromadb.config.isPersistent | quote }}
