# Karpenter Provider OCI
#
# Copyright (c) 2026 Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/

apiVersion: v1
kind: Secret
metadata:
  name: ocir-secret
  namespace: default
data:
  #replace it with base64 of ~/.docker/config.json
  .dockerconfigjson:
type: kubernetes.io/dockerconfigjson
