{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "stresstesting-bridges-load-generator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "stresstesting-bridges-load-generator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: web-ui
  selector:
    {{- include "stresstesting-bridges-load-generator.selectorLabels" . | nindent 4 }}
{{- end }}
